import type { Locale } from "./config";

export const copy = {
  pt: {
    skip: "Ir para o conteúdo",
    labAria: "Início do Systems Lab",
    navAria: "Principal",
    nav: {
      home: "Home",
      work: "Trabalhos",
      profile: "Perfil",
    },
    langAria: "Versão em inglês",
    hi: "Olá, eu sou",
    heroBefore: "Projeto ",
    heroAccent: "sistemas",
    heroAfter: ", infraestrutura de dados e ferramentas de software",
    workEyebrow: "Meu trabalho",
    role: "Engenheiro backend",
    openToWork: "Aberto a trabalho",
    place: "São Paulo, Brasil",
    stack: "Tecnologias e ferramentas",
    proposition:
      "Projetar sistemas, infraestrutura de dados e ferramentas de software com arquitetura clara, decisões justificadas e execução reproduzível.",
    heroLead: "Projeto sistemas, infraestrutura de dados e ferramentas de software.",
    bio: "Este site é o arquivo de um laboratório pessoal: cada peça é um sistema documentado, não uma lista de tecnologias.",
    profileBlurb:
      "Trabalho com APIs, regras de negócio e dados. Nos projetos abaixo, mostro o código, as decisões e o que ainda falta resolver.",
    profileCta: "Perfil completo",
    scroll: "Rolar",
    systems: "Projetos",
    featured: "Em destaque",
    areasTitle: "O que eu faço?",
    statusTitle: "Em foco",
    building: "Projeto principal",
    availability: "Disponibilidade",
    availabilityValue: "Aberto a oportunidades em backend",
    contactCta: "Há um sistema que vale construir?",
    contactLead: "E-mail, LinkedIn e GitHub. Sem formulário obrigatório.",
    hire: "Começar uma conversa",
    github: "GitHub",
    email: "E-mail",
    linkedin: "LinkedIn",
    cv: "CV (PDF)",
    resumeWeb: "Currículo",
    evidence: "Repositório de evidência",
    evidenceSoon: "Repositório de evidência indisponível.",
    demo: "Demonstração",
    docs: "Documentação",
    back: "Trabalhos",
    workTitle: "Índice de sistemas",
    workLead: "Explore os projetos por domínio, tecnologia, ano ou status",
    filterDomain: "Domínio",
    filterTech: "Tecnologia",
    filterYear: "Ano",
    filterStatus: "Status",
    filterAll: "Todos",
    filterEmpty: "Nenhum sistema neste recorte.",
    resetFilters: "Limpar filtros",
    profileTitle: "Perfil",
    contactTitle: "Contato",
    resumeTitle: "Currículo",
    resumeLead: "Resumo online do perfil e dos projetos. Baixe o currículo completo em PDF.",
    artifactLabel: "Núcleo computacional modular",
    footer: "Computational Engineering Archive",
    ogSite: "Systems Lab",
    section: {
      context: "01 / Contexto e problema",
      role: "02 / Papel e escopo",
      architecture: "03 / Arquitetura do sistema",
      data: "04 / Modelo de dados",
      decisions: "05 / Decisões de engenharia",
      implementation: "06 / Implementação",
      product: "07 / Experiência de produto",
      results: "08 / Resultados",
      retro: "09 / Retrospectiva",
    },
    domains: {
      Backend: "Backend",
      Data: "Dados",
      Automation: "Automação",
      "Developer Tools": "Ferramentas",
      "Systems Design": "Desenho de sistemas",
      Experiments: "Experimentos",
    },
    statuses: {
      active: "Ativo",
      archived: "Arquivo",
      lab: "Lab",
    },
    areas: [
      {
        title: "Arquitetura e APIs",
        body: "Defino entradas, respostas e tratamento de falhas das APIs, incluindo conflitos de sincronização entre o PDV e o servidor",
      },
      {
        title: "Modelagem e processamento de dados",
        body: "Modelo produtos, vendas e estoque no PostgreSQL e registros locais no SQLite para sincronização do PDV",
      },
      {
        title: "Automação e ferramentas internas",
        body: "Escrevo scripts para executar tarefas recorrentes e repetir cenários de demonstração e recuperação dos projetos",
      },
      {
        title: "Ambientes reproduzíveis",
        body: "Configuro ambientes locais e documento comandos de execução e teste, incluindo o laboratório Kubernetes do Observa",
      },
      {
        title: "Documentação e decisões",
        body: "Documento decisões de arquitetura, contratos e limitações junto ao código, com passos para verificar os resultados",
      },
    ],
  },
  en: {
    skip: "Skip to content",
    labAria: "Systems Lab home",
    navAria: "Primary",
    nav: {
      home: "Home",
      work: "Work",
      profile: "Profile",
    },
    langAria: "Portuguese version",
    hi: "Hi, I'm",
    heroBefore: "Designing ",
    heroAccent: "systems",
    heroAfter: ", data infrastructure, and software tools",
    workEyebrow: "My work",
    role: "Backend Engineer",
    openToWork: "Open to work",
    place: "São Paulo, Brazil",
    stack: "Technologies and tools",
    proposition:
      "Design systems, data infrastructure, and software tools with clear architecture, justified decisions, and reproducible execution.",
    heroLead: "Designing systems, data infrastructure, and software tools.",
    bio: "This site is the archive of a personal lab: each piece is a documented system, not a technology list.",
    profileBlurb:
      "I work on APIs, business rules, and data. The projects below show the code, the decisions, and the work still left to do.",
    profileCta: "Full profile",
    scroll: "Scroll",
    systems: "Projects",
    featured: "Featured",
    areasTitle: "What I do?",
    statusTitle: "In focus",
    building: "Main project",
    availability: "Availability",
    availabilityValue: "Open to backend engineering roles",
    contactCta: "Have a system worth building?",
    contactLead: "Email, LinkedIn, and GitHub. No required form.",
    hire: "Start a conversation",
    github: "GitHub",
    email: "Email",
    linkedin: "LinkedIn",
    cv: "CV (PDF)",
    resumeWeb: "Resume",
    evidence: "Evidence repository",
    evidenceSoon: "Evidence repository unavailable.",
    demo: "Demo",
    docs: "Documentation",
    back: "Work",
    workTitle: "System index",
    workLead: "Browse projects by domain, technology, year, or status",
    filterDomain: "Domain",
    filterTech: "Technology",
    filterYear: "Year",
    filterStatus: "Status",
    filterAll: "All",
    filterEmpty: "No systems in this cut.",
    resetFilters: "Clear filters",
    profileTitle: "Profile",
    contactTitle: "Contact",
    resumeTitle: "Resume",
    resumeLead: "Online summary of the profile and projects. Download the full resume as a PDF.",
    artifactLabel: "Modular computational core",
    footer: "Computational Engineering Archive",
    ogSite: "Systems Lab",
    section: {
      context: "01 / Context & problem",
      role: "02 / Role & scope",
      architecture: "03 / System architecture",
      data: "04 / Data model",
      decisions: "05 / Engineering decisions",
      implementation: "06 / Implementation",
      product: "07 / Product experience",
      results: "08 / Results",
      retro: "09 / Retrospective",
    },
    domains: {
      Backend: "Backend",
      Data: "Data",
      Automation: "Automation",
      "Developer Tools": "Developer tools",
      "Systems Design": "Systems design",
      Experiments: "Experiments",
    },
    statuses: {
      active: "Active",
      archived: "Archive",
      lab: "Lab",
    },
    areas: [
      {
        title: "Architecture and APIs",
        body: "I define API inputs, responses, and failure handling, including synchronization conflicts between the POS and server",
      },
      {
        title: "Data modeling and processing",
        body: "I model products, sales, and inventory in PostgreSQL and local records in SQLite for POS synchronization",
      },
      {
        title: "Automation and internal tools",
        body: "I write scripts for recurring tasks and repeatable project demonstration and recovery scenarios",
      },
      {
        title: "Reproducible environments",
        body: "I configure local environments and document run and test commands, including the Observa Kubernetes lab",
      },
      {
        title: "Documentation and decisions",
        body: "I document architecture decisions, contracts, and limitations beside the code, with steps to verify results",
      },
    ],
  },
} as const;

export type Copy = (typeof copy)[Locale];
