import type { Locale } from "./config";

export const copy = {
  pt: {
    skip: "Ir para o conteúdo",
    labAria: "Início do Systems Lab",
    navAria: "Principal",
    nav: {
      home: "Home",
      work: "Trabalhos",
      profile: "Perfil",
    },
    langAria: "Versão em inglês",
    hi: "Olá, eu sou",
    heroBefore: "Estudante de ADS na FATEC Ipiranga, aberto a ",
    heroAccent: "estágio",
    heroAfter: " e a vaga júnior em backend",
    workEyebrow: "Meu trabalho",
    role: "Desenvolvedor backend",
    openToWork: "Aberto a estágio e júnior",
    formation: "Cursando Análise e Desenvolvimento de Sistemas na FATEC Ipiranga desde fevereiro de 2026.",
    place: "São Paulo, Brasil",
    stack: "Tecnologias e ferramentas",
    proposition:
      "Estudante de ADS na FATEC Ipiranga, em busca de estágio ou vaga júnior em backend. Os projetos mostram a API, a decisão e o limite.",
    heroLead: "Estudante de ADS na FATEC Ipiranga, aberto a estágio e a vaga júnior em backend.",
    bio: "Este site é o arquivo de um laboratório pessoal: cada peça é um sistema documentado, não uma lista de tecnologias.",
    profileBlurb:
      "Estudo ADS na FATEC Ipiranga. Nos projetos desta página, o código, a decisão e o que ainda falta ficam juntos.",
    profileCta: "Perfil completo",
    profileLead:
      "Estudo Análise e Desenvolvimento de Sistemas na FATEC Ipiranga e busco estágio ou uma vaga júnior em backend. Nos projetos, a API, a regra e o caminho do dado ficam ao lado do que ainda falta resolver.",
    profileHowTitle: "Como trabalho",
    profileHow: [
      "Começo pelo caso que o sistema precisa aguentar: uma venda sem API, um pedido pago sem estoque, um redirect que não espera o analytics.",
      "O contrato vem antes da ferramenta: status, identificador e o que permanece local até o servidor aceitar.",
      "O limite fica ao lado do resultado. Medição de laboratório permanece medição de laboratório.",
    ],
    profileSkillsTitle: "No código",
    profileSkills:
      "No Mercado One, a API é Java com Spring Boot, o administrativo é Angular e o caixa é JavaFX, com PostgreSQL no servidor e SQLite no PDV. O administrativo e a API rodam num piloto na Azure; o PDV permanece no caixa. Observa e o pipeline de pedidos usam Python e Node.js em serviços ligados por eventos: o primeiro em Kafka e Kubernetes local, o segundo em RabbitMQ. O encurtador coloca Go no redirect, Redis no cache e PostgreSQL como fonte da verdade. Docker sobe esses ambientes.",
    scroll: "Rolar",
    systems: "Projetos",
    featured: "Em destaque",
    areasTitle: "Na prática",
    statusTitle: "Em foco",
    building: "Projeto principal",
    availability: "Disponibilidade",
    availabilityValue: "Estágio ou júnior em backend",
    contactCta: "Busco estágio ou uma vaga júnior em backend",
    contactLead: "E-mail, LinkedIn e GitHub. Sem formulário obrigatório.",
    hire: "Começar uma conversa",
    github: "GitHub",
    email: "E-mail",
    linkedin: "LinkedIn",
    cv: "CV (PDF)",
    resumeWeb: "Currículo",
    evidence: "Repositório de evidência",
    evidenceSoon: "Repositório de evidência indisponível.",
    demo: "Demonstração",
    docs: "Documentação",
    back: "Trabalhos",
    workTitle: "Índice de sistemas",
    workLead: "Explore os projetos por domínio, tecnologia, ano ou status",
    filterDomain: "Domínio",
    filterTech: "Tecnologia",
    filterYear: "Ano",
    filterStatus: "Status",
    filterAll: "Todos",
    filterEmpty: "Nenhum sistema neste recorte.",
    resetFilters: "Limpar filtros",
    profileTitle: "Perfil",
    contactTitle: "Contato",
    resumeTitle: "Currículo",
    resumeLead: "Resumo online do perfil e dos projetos. Baixe o currículo completo em PDF.",
    artifactLabel: "Núcleo computacional modular",
    footer: "Computational Engineering Archive",
    ogSite: "Systems Lab",
    section: {
      context: "01 / Contexto e problema",
      role: "02 / Papel e escopo",
      architecture: "03 / Arquitetura do sistema",
      data: "04 / Modelo de dados",
      decisions: "05 / Decisões de engenharia",
      implementation: "06 / Implementação",
      product: "07 / Experiência de produto",
      results: "08 / Resultados",
      retro: "09 / Retrospectiva",
    },
    domains: {
      Backend: "Backend",
      Data: "Dados",
      Automation: "Automação",
      "Developer Tools": "Ferramentas",
      "Systems Design": "Desenho de sistemas",
      Experiments: "Experimentos",
    },
    statuses: {
      active: "Ativo",
      archived: "Arquivo",
      lab: "Lab",
    },
    areas: [
      {
        title: "Arquitetura e APIs",
        body: "Defino entradas, respostas e tratamento de falhas das APIs, incluindo conflitos de sincronização entre o PDV e o servidor",
      },
      {
        title: "Modelagem e processamento de dados",
        body: "Modelo produtos, vendas e estoque no PostgreSQL e registros locais no SQLite para sincronização do PDV",
      },
      {
        title: "Automação e ferramentas internas",
        body: "Escrevo scripts para executar tarefas recorrentes e repetir cenários de demonstração e recuperação dos projetos",
      },
      {
        title: "Ambientes reproduzíveis",
        body: "Configuro ambientes locais e documento comandos de execução e teste, incluindo o laboratório Kubernetes do Observa",
      },
      {
        title: "Documentação e decisões",
        body: "Documento decisões de arquitetura, contratos e limitações junto ao código, com passos para verificar os resultados",
      },
    ],
  },
  en: {
    skip: "Skip to content",
    labAria: "Systems Lab home",
    navAria: "Primary",
    nav: {
      home: "Home",
      work: "Work",
      profile: "Profile",
    },
    langAria: "Portuguese version",
    hi: "Hi, I'm",
    heroBefore: "ADS student at FATEC Ipiranga, open to an ",
    heroAccent: "internship",
    heroAfter: " or a junior backend role",
    workEyebrow: "My work",
    role: "Backend developer",
    openToWork: "Open to internship and junior roles",
    formation: "Studying Systems Analysis and Development at FATEC Ipiranga since February 2026.",
    place: "São Paulo, Brazil",
    stack: "Technologies and tools",
    proposition:
      "ADS student at FATEC Ipiranga, looking for an internship or a junior backend role. The projects show the API, the decision, and the limit.",
    heroLead: "ADS student at FATEC Ipiranga, open to an internship or a junior backend role.",
    bio: "This site is the archive of a personal lab: each piece is a documented system, not a technology list.",
    profileBlurb:
      "I study ADS at FATEC Ipiranga. In the projects on this page, the code, the decision, and the work still left sit together.",
    profileCta: "Full profile",
    profileLead:
      "I study Systems Analysis and Development at FATEC Ipiranga and I am looking for an internship or a junior backend role. In the projects, the API, the rule, and the path the data takes sit next to the work still open.",
    profileHowTitle: "How I work",
    profileHow: [
      "I start from the case the system has to survive: a sale with no API, a paid order with no stock, a redirect that does not wait for analytics.",
      "The contract comes before the tool: status, identifier, and what stays local until the server accepts it.",
      "The limit sits next to the result. A lab measurement stays a lab measurement.",
    ],
    profileSkillsTitle: "In the code",
    profileSkills:
      "In Mercado One, the API is Java with Spring Boot, the admin is Angular, and the POS is JavaFX, with PostgreSQL on the server and SQLite on the POS. The admin and API run on an Azure pilot; the POS stays on the register. Observa and the order pipeline use Python and Node.js in event-driven services: the first on Kafka and local Kubernetes, the second on RabbitMQ. The shortener puts Go on the redirect, Redis on the cache, and PostgreSQL as the source of truth. Docker starts these environments.",
    scroll: "Scroll",
    systems: "Projects",
    featured: "Featured",
    areasTitle: "In practice",
    statusTitle: "In focus",
    building: "Main project",
    availability: "Availability",
    availabilityValue: "Internship or junior backend",
    contactCta: "Looking for an internship or a junior backend role",
    contactLead: "Email, LinkedIn, and GitHub. No required form.",
    hire: "Start a conversation",
    github: "GitHub",
    email: "Email",
    linkedin: "LinkedIn",
    cv: "CV (PDF)",
    resumeWeb: "Resume",
    evidence: "Evidence repository",
    evidenceSoon: "Evidence repository unavailable.",
    demo: "Demo",
    docs: "Documentation",
    back: "Work",
    workTitle: "System index",
    workLead: "Browse projects by domain, technology, year, or status",
    filterDomain: "Domain",
    filterTech: "Technology",
    filterYear: "Year",
    filterStatus: "Status",
    filterAll: "All",
    filterEmpty: "No systems in this cut.",
    resetFilters: "Clear filters",
    profileTitle: "Profile",
    contactTitle: "Contact",
    resumeTitle: "Resume",
    resumeLead: "Online summary of the profile and projects. Download the full resume as a PDF.",
    artifactLabel: "Modular computational core",
    footer: "Computational Engineering Archive",
    ogSite: "Systems Lab",
    section: {
      context: "01 / Context & problem",
      role: "02 / Role & scope",
      architecture: "03 / System architecture",
      data: "04 / Data model",
      decisions: "05 / Engineering decisions",
      implementation: "06 / Implementation",
      product: "07 / Product experience",
      results: "08 / Results",
      retro: "09 / Retrospective",
    },
    domains: {
      Backend: "Backend",
      Data: "Data",
      Automation: "Automation",
      "Developer Tools": "Developer tools",
      "Systems Design": "Systems design",
      Experiments: "Experiments",
    },
    statuses: {
      active: "Active",
      archived: "Archive",
      lab: "Lab",
    },
    areas: [
      {
        title: "Architecture and APIs",
        body: "I define API inputs, responses, and failure handling, including synchronization conflicts between the POS and server",
      },
      {
        title: "Data modeling and processing",
        body: "I model products, sales, and inventory in PostgreSQL and local records in SQLite for POS synchronization",
      },
      {
        title: "Automation and internal tools",
        body: "I write scripts for recurring tasks and repeatable project demonstration and recovery scenarios",
      },
      {
        title: "Reproducible environments",
        body: "I configure local environments and document run and test commands, including the Observa Kubernetes lab",
      },
      {
        title: "Documentation and decisions",
        body: "I document architecture decisions, contracts, and limitations beside the code, with steps to verify results",
      },
    ],
  },
} as const;

export type Copy = (typeof copy)[Locale];
